export const LOADING = "LOADING";
export const ERROR = "ERROR";

export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";

export const EDITING_TASK_SUCCESS = "EDITING_TASK_SUCCESS";
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS";

export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADDING_TASK_SUCCESS = "ADDING_TASK_SUCCESS";

export const REMOVING_TASK = "REMOVING_TASK";
export const REMOVE_TASK_SUCCESS="REMOVE_TASK_SUCCESS";

export const REMOVING_MULTIPLE_TASKS = "REMOVING-MULTIPLE_TASKS";
export const REMOVE_MULTIPLE_TASKS_SUCCESS="REMOVE_MULTIPLE_TASKS_SUCCESS";
